### ISSUE TITLE
Unable to import: "Error getting field map settings"

### ISSUE THREAD

**Issue by allisonvsp** [bullhorn/dataloader-app#2]
Hello,
I'm helping a client with their dataloader access.  I downloaded the latest dataloader version (2.2.1) for some tests. I fill out all required information. When I click 'check credentials' it says - **login validated**. But when I go on to load a very simple test csv for a candidate import, I get the following error:
![image (1)](https://user-images.githubusercontent.com/71700662/93869269-dc220880-fccb-11ea-857c-55dbfca2aa0d.png)

So far I've tried:
- Reset the user password
- Checking all required settings for the REST API keys
- Re-saved the user type created 

The username that's being tested with is:
broadwick.dataloader

Whatever I try I can't seem to get past that error. Any advice?

**Comment by ndickerson** [comment]
Has this worked before, or has it always has this issue? Does this happen with any input file, or only certain input files?

**Comment by ndickerson** [comment]
Closing this for now since I believe this was an isolated login issue. Feel feel to reopen the issue if this is still ongoing.

**Comment by ndickerson** [comment]
Re-opening. Found the bug - fixing it in a release today.

**Comment by ndickerson** [comment]
Fixed - releasing the newest version with this fix in it now: https://github.com/bullhorn/dataloader-app/releases

**Comment by jchrister-acr** [comment]
Hi, good morning. I'm using v2.4.0 which I believe is the latest release, and encountered this error again - 
![error field map settings](https://user-images.githubusercontent.com/88651884/128674937-c1376979-9369-4063-b040-64ea63899b10.PNG)
I've tried with two different api logins, both of which validate but then encounter this same error, and tried with a few different CSV files.
(As an aside - even though it's candidate data, the dataloader always seems to recognize it as a different record type. Don't know if that's relevant or not)
Do you have any additional suggestions?
