### ISSUE TITLE
Mac OS app check credential/ Field map scrape failure 

### ISSUE THREAD

**Issue by mathewfinley** [bullhorn/dataloader-app#3]
- Latest OS X update does not allow api credentials to verify 
- This ultimately blocks you from continuing in the GUI, due to the app not being able to gather Field Map settings

**Comment by ndickerson** [comment]
Currently working on a fix for this. The underlying issue is that the latest Mac versions are using a newer version of Java than the Data Loader app is built with.

**Comment by ndickerson** [comment]
This has been fixed, and the [new version](https://github.com/bullhorn/dataloader-app/releases) is being released later today. After today, the app should auto-update to the newest version after it's opened for a minute. The next time you open the app it should be the upgraded version.
