### ISSUE TITLE
Client records being processed as Opportunities

### ISSUE THREAD

**Issue by NolaVlasek** [bullhorn/dataloader-app#5]
Every time we try to upload ClientContact records, they are being processed as Opportunities and then don't load at all. We've cleared our cache and selected ClientContact as the entity
![Data Loader Error 1](https://user-images.githubusercontent.com/83998459/117755242-31ad2480-b25f-11eb-8d5e-89a1ea92cc41.JPG)
![Data Loader Error 2](https://user-images.githubusercontent.com/83998459/117755246-32de5180-b25f-11eb-8912-88e73a240382.JPG)
![Data Loader Error 3](https://user-images.githubusercontent.com/83998459/117755247-3376e800-b25f-11eb-83b1-7815651d124e.JPG)

**Comment by ndickerson** [comment]
Sorry, I am just seeing this - Is this still a show-stopper? You'll want to inspect the log file that got generated and attach that to this issue so that I can triage what's happening.

**Comment by NolaVlasek** [comment]
Hi Nathan,

Thanks for getting back to us. We are still experiencing issues when trying to upload our test CSV of Client Contacts. I will attach the most recent run. I’ve also noticed no matter what entity we set in the beginning, when we click Next it looks like it has been set to the Opportunities entity, which has the target icon and a purple banner. You can see this in the screenshot below. This appears when I try to upload Candidates or Clients:
***@***.***D761DB.24B78CE0]

Please let me know if you need any more of our logs or any other information. I’ve also cc’d in my manager, Sanne Del so she is across everything.

Thanks,
Nola


Six Degrees Executive acknowledges the Traditional Owners of the lands on which we work and live. We strive to promote flexibility, diversity, inclusion and belonging in all that we do.

NOLA VLASEK
Systems and Data Analyst


P +61 3 8613 3500
E ***@***.******@***.***>

[cid:sde-logo-_3f1e334c-4576-4e41-9e53-0d85f14f118b.jpg]

Level 5, 484 St Kilda Road, Melbourne, 3004

**Comment by ndickerson** [comment]
I think that somehow the auto-update or something related to the app itself and the permissions it has to run and update the Date Loader java executable on your machine may be affecting this. 

Q: What happens when you change the title of the CSV file to 'ClientContact.csv' instead of `Export Test.csv`
Q: What version of the app do you have installed? Is it the latest 2.3.1?
Q: If you're not on the latest, what happens when you uninstall your app and re-install the latest? (no data files are lost in the process)

**Comment by NolaVlasek** [comment]
Hi Nathan,

We ended up sorting this out, thanks for getting back to us.

Nola


Six Degrees Executive acknowledges the Traditional Owners of the lands on which we work and live. We strive to promote flexibility, diversity, inclusion and belonging in all that we do.

NOLA VLASEK
Systems and Data Analyst


P +61 3 8613 3500
E ***@***.******@***.***>

[cid:sde-logo-_3f1e334c-4576-4e41-9e53-0d85f14f118b.jpg]<https://sixd.careers/home>

Level 5, 484 St Kilda Road, Melbourne, 3004

<https://sixd.careers/home><https://sixd.careers/NOLA-VLASEK>[cid:sde-dark-grey-icon_71eb914e-7f34-454f-b309-2bf1f61abec4.png]<https://www.sixdegreesexecutive.com.au/>[cid:linkedin-dark-grey-icon_6b8dc682-82e7-460d-959f-72904e02f133.png]<https://www.linkedin.com/company/six-degrees-executive/><https://sixd.careers/facebook>[cid:insta-dark-grey-icon_bef15de9-72cf-4201-811d-8470ee1b83ec.png]<https://www.instagram.com/sixdegreesexecutive/>[cid:fb-dark-grey-icon_00e57c71-5f50-4888-939b-3812d05dde1e.png]<https://www.facebook.com/sixdegreesrecruiters/>[cid:twitter-grey-iconcopy2_aefb7e96-9f80-4174-8845-870d19df9861.png]<https://twitter.com/sixdegreesexec>
